# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GPS.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GPS.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\tGPS.proto\"[\n\x03GPS\x12\x10\n\x08latitude\x18\x01 \x02(\x02\x12\x11\n\tlongitude\x18\x02 \x02(\x02\x12\x12\n\nsatellites\x18\x03 \x02(\r\x12\r\n\x05speed\x18\x04 \x02(\x02\x12\x0c\n\x04\x64\x61te\x18\x05 \x02(\t\"\x1f\n\x04Trip\x12\x17\n\tlocations\x18\x01 \x03(\x0b\x32\x04.GPS')
)




_GPS = _descriptor.Descriptor(
  name='GPS',
  full_name='GPS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='GPS.latitude', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='GPS.longitude', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='satellites', full_name='GPS.satellites', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='GPS.speed', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date', full_name='GPS.date', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=104,
)


_TRIP = _descriptor.Descriptor(
  name='Trip',
  full_name='Trip',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='locations', full_name='Trip.locations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=137,
)

_TRIP.fields_by_name['locations'].message_type = _GPS
DESCRIPTOR.message_types_by_name['GPS'] = _GPS
DESCRIPTOR.message_types_by_name['Trip'] = _TRIP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GPS = _reflection.GeneratedProtocolMessageType('GPS', (_message.Message,), dict(
  DESCRIPTOR = _GPS,
  __module__ = 'GPS_pb2'
  # @@protoc_insertion_point(class_scope:GPS)
  ))
_sym_db.RegisterMessage(GPS)

Trip = _reflection.GeneratedProtocolMessageType('Trip', (_message.Message,), dict(
  DESCRIPTOR = _TRIP,
  __module__ = 'GPS_pb2'
  # @@protoc_insertion_point(class_scope:Trip)
  ))
_sym_db.RegisterMessage(Trip)


# @@protoc_insertion_point(module_scope)
